"""Create tables User, Channel

Revision ID: 1577faf2b5e1
Revises: 
Create Date: 2022-03-09 06:01:26.420292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1577faf2b5e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('media_mode', sa.Boolean(), nullable=False),
    sa.Column('reply_mode', sa.Boolean(), nullable=False),
    sa.Column('forward_mode', sa.Boolean(), nullable=False),
    sa.Column('pixiv_style', sa.Integer(), nullable=False),
    sa.Column('last_info', sa.JSON(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('last_post', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    op.drop_table('user')
    # ### end Alembic commands ###
